package ziad_mrx.samsung.a20s.wifip2p.gsi_fixes;

import static de.robv.android.xposed.XposedHelpers.findAndHookMethod;
import static de.robv.android.xposed.XposedHelpers.setObjectField;

import android.annotation.SuppressLint;
import android.net.wifi.WpsInfo;
import android.net.wifi.p2p.WifiP2pConfig;
import android.net.wifi.p2p.WifiP2pDevice;
import android.net.wifi.p2p.WifiP2pGroup;
import android.net.wifi.p2p.WifiP2pWfdInfo;
import android.os.Handler;
import android.os.Message;

import java.lang.reflect.Constructor;

import de.robv.android.xposed.IXposedHookLoadPackage;
import de.robv.android.xposed.XC_MethodHook;
import de.robv.android.xposed.XC_MethodReplacement;
import de.robv.android.xposed.XposedBridge;
import de.robv.android.xposed.XposedHelpers;
import de.robv.android.xposed.callbacks.XC_LoadPackage.LoadPackageParam;
// for file handling (reading from our p2p real-time events file)
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;
import java.util.HexFormat;


public class MainHook implements IXposedHookLoadPackage {
    private static final String TAG = "P2P_GSI_FIX: ";
    private Boolean hooksApplied = false;

    private Thread pollingThread = null;
    private volatile boolean isPolling = false;
    private Object mMonitorInstance = null;
    private String mInterfaceName = "wlan0";

    // the absolute path to the p2p_evt_recent file generated by the script that runs by the
    // magisk module that polls p2p events directly from logcat entries of wpa_supplicant.
    private String mP2pEvtRecentFFullPath = "/data/p2p_evt_recent";
    

    @Override
    public void handleLoadPackage(LoadPackageParam lpparam) throws Throwable {
        // We only care about the System Server (android)
        if (!lpparam.packageName.equals("android")) return;

        XposedBridge.log(TAG + "Monitoring Service Registration in System Server...");

        // Every service, even those from APEX, must register itself to be usable.
        // We hook the 'addService' method which is the "front desk" of all Android services.
        try {
            XposedHelpers.findAndHookMethod("android.os.ServiceManager", lpparam.classLoader,
                    "addService", String.class, android.os.IBinder.class, boolean.class, int.class, new XC_MethodHook() {
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                            String name = (String) param.args[0];

                            // Log everything related to wifi to catch the real name
                            if (name.toLowerCase().contains("wifi") || name.toLowerCase().contains("p2p")) {
                                XposedBridge.log(TAG + "SERVICE REGISTERED: " + name);

                                Object binder = param.args[1];
                                if ((binder != null) && !hooksApplied) {
                                    Class<?> binderClass = binder.getClass();
                                    XposedBridge.log(TAG + "Implementation Class: " + binderClass.getName());

                                    // Apply hooks using the ClassLoader that owns this binder
                                    applyHooks(binderClass.getClassLoader());
                                }
                            }
                        }
                    });
        } catch (Throwable t) {
            XposedBridge.log(TAG + "Error: Couldn't hook into method \"addService\": " + t.getMessage());
        }
    }


    private java.lang.reflect.Method recursiveFindMethod(Class<?> clazz, String namePart, Class<?> returnType) {
        Class<?> current = clazz;
        while (current != null && current != Object.class) {
            for (java.lang.reflect.Method m : current.getDeclaredMethods()) {
                // Match name and return type (handling void.class correctly)
                if (m.getName().toLowerCase().contains(namePart.toLowerCase()) &&
                        (returnType == null || m.getReturnType() == returnType)) {
                    return m;
                }
            }
            current = current.getSuperclass(); // Move to the parent class
        }
        return null;
    }


    private void applyHooks(ClassLoader cloader) {
        // a control variable to indicate if any exception has occured while trying to hook to methods of ANY class.
        boolean exceptionsOccured = false;
        Class<?> p2pNative = XposedHelpers.findClassIfExists("com.android.server.wifi.p2p.WifiP2pNative", cloader);
        if (p2pNative == null) {
            XposedBridge.log(TAG + "Couldn't find com.android.server.wifi.p2p.WifiP2pNative!");
            return;
        };
        // if we don't return at this point, it means we have found the WifiP2pNative class!
        XposedBridge.log(TAG + "Found com.android.server.wifi.p2p.WifiP2pNative!");
        // 1. Force WifiP2pNative to report wlan0 as the interface
        try {
            for (java.lang.reflect.Method m : p2pNative.getMethods()) {
                // getInterfaceName() method hook so that it would always return wlan0
                if ((m.getReturnType() == String.class) && (m.getName().toLowerCase().contains("interfacename"))) {
                    XposedBridge.hookMethod(m, new XC_MethodReplacement() {
                        @Override
                        protected Object replaceHookedMethod(MethodHookParam param) throws Throwable {
                            return "wlan0";
                        }
                    });
                }
                if ((m.getReturnType() == String.class) && (m.getName().toLowerCase().contains("setupinterface"))) {
                    // at this point m is a java.lang.reflect.Method instance of the WifiP2pNative's Method named
                    // setupInterface()
                    XposedBridge.hookMethod(m, new XC_MethodHook() {
                        @Override
                        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                            XposedBridge.log(TAG + "setupInterface() was called!, starting the Peer polling process...");
                            startP2pPeerPolling();
                            param.setResult("wlan0");
                        }
                    });
                }
                if (
                        (m.getReturnType() == void.class) && (m.getName().toLowerCase().contains("teardowninterface"))
                ) {
                    XposedBridge.hookMethod(m, new XC_MethodHook() {
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                            XposedBridge.log(TAG + "teardownInterface() was called!, Stopping the P2P Peers poller thread...");
                            stopP2pPeerPolling();
                        }
                    });
                }
                if (
                        (m.getReturnType() == String.class) && (
                                (m.getName().toLowerCase().contains("p2pconnect")) ||
                                        (m.getName().toLowerCase().contains("connect"))
                                ) && (m.getParameterCount() >= 2)
                ) {
                    // hook into P2pConnect()
                    XposedBridge.hookMethod(m, new XC_MethodHook() {
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                            XposedBridge.log(TAG + "p2pConnect() method called with Args: ");
                            WifiP2pConfig p2pcfg = (WifiP2pConfig) param.args[0];
                            // list out all data inside the WifiP2pConfig object.
                            XposedBridge.log(TAG + "[0]: WifiP2pConfig.deviceAddress: " + p2pcfg.deviceAddress);
                            XposedBridge.log(TAG + "[0]: WifiP2pConfig.groupOwnerIntent: " + Integer.toString(p2pcfg.groupOwnerIntent));
                            XposedBridge.log(TAG + "[0]: WifiP2pConfig.wps (WpsInfo object).BSSID: " + p2pcfg.wps.BSSID);
                            XposedBridge.log(TAG + "[0]: WifiP2pConfig.wps.pin: " + p2pcfg.wps.pin);
                            XposedBridge.log(TAG + "[0]: WifiP2pConfig.wps.setup: " + Integer.toString(p2pcfg.wps.setup));
                            for (int i = 1; i < param.args.length; i++) {
                                XposedBridge.log(TAG + "[" + i + "]: " + param.args[i] + "  ");
                            }
                        }

                        @Override
                        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                            XposedBridge.log(TAG + "p2pConnect() returned " + param.getResult());
                        }
                    });
                }
                // hook into P2pInvite()
                if (
                        (m.getName().toLowerCase().contains("p2pinvite")) ||
                                (m.getName().toLowerCase().contains("invite"))
                ) {
                    XposedBridge.hookMethod(m, new XC_MethodHook() {
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                            XposedBridge.log(TAG + "p2pInvite() called with args: ");
                            // it accepts 2 params, WifiP2pGroup as first param, deviceAddress (String) as second param
                            WifiP2pGroup p2pgrp = (WifiP2pGroup) param.args[0];
                            XposedBridge.log(TAG + "[0]: WifiP2pGroup.getInterface(): " + p2pgrp.getInterface());
                            XposedBridge.log(TAG + "[0]: WifiP2pGroup.getNetworkName(): " + p2pgrp.getNetworkName());
                            XposedBridge.log(TAG + "[0]: WifiP2pGroup.toString(): " + p2pgrp.toString());
                            // the second index (1) is the device address.
                            XposedBridge.log(TAG + "device Address: " + param.args[1]);
                        }

                        @Override
                        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                            XposedBridge.log(TAG + "p2pInvite() returned : " + param.getResult());
                        }
                    });
                }
            }
        } catch (Throwable t) {
            XposedBridge.log(TAG + "Failed to hook WifiP2pNative: " + t.getMessage());
            exceptionsOccured = true;
        }

        Class<?> P2pMonitor = XposedHelpers.findClassIfExists("com.android.server.wifi.p2p.WifiP2pMonitor", cloader);
        if (P2pMonitor != null) {
            XposedBridge.log(TAG + "Found com.android.server.wifi.p2p.WifiP2pMonitor!");
            // 2. Redirect the Monitor to listen for P2P events on the wlan0 socket
            try {
                for (java.lang.reflect.Method m : P2pMonitor.getDeclaredMethods()) {
                    if (m.getName().toLowerCase().contains("registerhandler")) {
                        XposedBridge.hookMethod(m, new XC_MethodHook() {
                            @Override
                            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                                if (mMonitorInstance == null) {
                                    XposedBridge.log(TAG + "Captured WifiP2pMonitor instance from the \"this\" object of a registerHandler() call!");
                                    mMonitorInstance = param.thisObject;
                                }
                                XposedBridge.log(TAG + "Redirected register handler to wlan0");
                                param.args[0] = "wlan0";
                            }
                        });
                    }
                    if (m.getName().toLowerCase().contains("dispatchevent")) {
                        // we will be hooking into dispatch event just for logging purposes.
                        XposedBridge.hookMethod(m, new XC_MethodHook() {
                            @Override
                            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                                // first parameter is a friendly name for the Wi-Fi hardware event received.
                                String evtName = (String) param.args[0];
                                // log in Xposed log.
                                XposedBridge.log(TAG + "WiFi P2P Event: " + evtName);


                            }
                        });
                    }
                }

            } catch (Throwable t) {
                XposedBridge.log(TAG + "Failed to hook WifiP2pMonitor: " + t.getMessage());
                exceptionsOccured = true;
            }
        } else {
            XposedBridge.log(TAG + "Error: couldn't find WifiP2pMonitor class!");
            exceptionsOccured = true;
        }


        // 3. Prevent the StateMachine from shutting down discovery due to 'Block' or 'Fail' messages
        try {
            Class<?> baseStateClass = XposedHelpers.findClass("com.android.internal.util.State", cloader);
            java.lang.reflect.Method processMsgMethod = null;
            // we will find it manually since we aren't sure what its signature is
            for (java.lang.reflect.Method m : baseStateClass.getMethods()) {
                if ((m.getName().toLowerCase().contains("processmessage")) && (m.getReturnType() == boolean.class)) {
                    processMsgMethod = m;
                    break;
                }
            }
            // at this point, we may have found it or not, if we haven't still found it, we throw a Throwable.
            // whether or not we found it is indicated by whether or not the value of it is null.
            if (processMsgMethod != null) {
                // we found it, therefore we must hook into it.
                XposedBridge.hookMethod(processMsgMethod, new XC_MethodHook() {
                    @Override
                    protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                        // we need to get the name of the caller class.
                        String callerCName = param.thisObject.getClass().getName();
                        Message msg = (Message) param.args[0];
                        XposedBridge.log(TAG + "State.processMessage: " + msg.what + " from " + callerCName);
                        if (callerCName.toLowerCase().contains("wifip2pserviceimpl")) { // assuming they've messed the casing of it.
                            // the first parameter of this method call is a Message object.
                            // which is the message we do want to process.
//                            Message msg = (Message) param.args[0];
                            // 155446: BLOCK_DISCOVERY
                            // 139269: DISCOVER_PEERS_FAILED
                            // 139235: STOP_DISCOVERY
                            XposedBridge.log(TAG + "Got P2P message: " + msg.what + " from State: " + param.thisObject.getClass().getSimpleName());
                            if (
                                    (msg.what == 155446) ||
                                            (msg.what == 139269) ||
                                            (msg.what == 139235)
                            ) {
                                // these are the messages we want to ignore.
                                // so if they occur we will ignore them.
                                XposedBridge.log(TAG + ">>>> INTERCEPTED P2P Message: " + msg.what + "!");
                                param.setResult(true);
                            }
                        }
                    }
                });
            } else {
                // the value is null, we will throw a Throwable
                throw new Throwable("Couldn't find method processMessage()");
            }
        } catch (Throwable t) {
            XposedBridge.log(TAG + "Failed to hook and modify base State class: " + t.getMessage());
            exceptionsOccured = true;
        }
        // hook P2pServiceImpl directly.
        try {
            Class<?> P2pSvcImpl = cloader.loadClass("com.android.server.wifi.p2p.WifiP2pServiceImpl");
            // we will load the com.android.internal.util.State class to check for assignability
            Class<?> stateCls = cloader.loadClass("com.android.internal.util.State");
            // find method setDiscoveryBlocked or best match
            java.lang.reflect.Method setdiscoveryblockedmethod = recursiveFindMethod(P2pSvcImpl, "setDiscoveryBlocked", void.class);
            if (setdiscoveryblockedmethod != null) {
                XposedBridge.hookMethod(setdiscoveryblockedmethod, new XC_MethodHook() {
                    @Override
                    protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                        // overwrite first param to false
                        XposedBridge.log(TAG + "System tried to block discovery, but prevented from doing so.");
                        param.args[0] = false;
                    }
                });
            }
            java.lang.reflect.Method updP2pDisallowedChannels = recursiveFindMethod(P2pSvcImpl, "updateP2pDisallowedChannels", void.class);
            if (updP2pDisallowedChannels != null) {
                XposedBridge.hookMethod(updP2pDisallowedChannels, new XC_MethodReplacement() {
                    @Override
                    protected Object replaceHookedMethod(MethodHookParam param) throws Throwable {
                        // preventing system from updating p2p disallowed channels
                        XposedBridge.log(TAG + "System has tried to update p2p disallowed channels, but is prevented from.");
                        return null;
                    }
                });
            }
            // we will hook into every `processMessage` override of every sub-class of the class `WifiP2pServiceImpl`
            for (Class<?> inner : P2pSvcImpl.getDeclaredClasses()) {
                if (stateCls.isAssignableFrom(inner)) {
                    // next up, we gotta iterate over each method inside the inner class
                    // since we know it is either a sub-class of the state class or
                    // an object/instance of that state class.
                    for (java.lang.reflect.Method m : inner.getDeclaredMethods()) {
                        // we will use getDeclaredMethods() here since we are only looking for overrides.
                        if (m.getName().equals("processMessage") && m.getReturnType() == boolean.class) {
                            // if the method's name is processMessage and has a return type of boolean
                            // then it is our desired processMessage method we do wanna hook into.
                            XposedBridge.hookMethod(m, new XC_MethodHook() {
                                @Override
                                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                                    Message msg = (Message) param.args[0]; // processMessage takes the first parameter as a Message object.
                                    String stateName = param.thisObject.getClass().getSimpleName();
                                    XposedBridge.log(TAG + "Got message: " + msg.what + " from State:  " + stateName);
                                    if (msg.what == 155446 || msg.what == 139269 || msg.what == 139235) {
                                        XposedBridge.log(TAG + "[" + stateName + "] INTERCEPTED Kill Command: " + msg.what);
                                        param.setResult(true); // Suppress
                                    }
                                }
                            });
                            break; // prevent unnecessary computations.
                        }
                    }
                }
            }
            // Hook the connect method that receives requests from apps
            for (java.lang.reflect.Method m : P2pSvcImpl.getDeclaredMethods()) {
                if (m.getName().toLowerCase().contains("connect")) {
                    // hook into this target method
                    XposedBridge.hookMethod(m, new XC_MethodHook() {
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                            XposedBridge.log(TAG + ">>> WifiP2pServiceImpl." + m.getName() + "() CALLED!");
                            XposedBridge.log(TAG + "    Param count: " + param.args.length);
                            for (int i = 0; i < param.args.length; i++) {
                                if (param.args[i] != null) {
                                    XposedBridge.log(TAG + "    arg[" + i + "]: " + param.args[i].getClass().getSimpleName());
                                }
                            }
                        }
                    });
                }
            }
        } catch (Throwable t) {
            XposedBridge.log(TAG + "Failed to hook into WifiP2pServiceImpl directly: " + t.getMessage());
            exceptionsOccured = true;
        }

        // indicate that hooks have been applied successfully!
        if (!exceptionsOccured) hooksApplied = true;
        return;
    }


    // Polling method to check for P2P peers
    private void startP2pPeerPolling() {
        if (pollingThread != null && pollingThread.isAlive()) {
            XposedBridge.log(TAG + "Polling thread already running");
            return;
        }

        isPolling = true;
        pollingThread = new Thread(new Runnable() {
            private java.util.Set<WifiP2pDevice> knownPeers = new java.util.HashSet<>();
            private String lastProcessedEvt = ""; // a string that holds the last processed event full string.
            @Override
            public void run() {
                XposedBridge.log(TAG + "Polling thread started");

                while (isPolling) {
                    try {
                        // before polling for peers, we will check for other P2P events from the file in
                        // /data/p2p_evt_recent
                        try {
                            // we will read from the file stored in mP2pEvtRecentFFullPath
                            String lastP2pEvtStr = new String(Files.readAllBytes(Paths.get(mP2pEvtRecentFFullPath))).replace("\n", "");
                            // but we must remove the last newline escape character from our string.
                            if (!lastP2pEvtStr.equalsIgnoreCase(lastProcessedEvt)) {
                                // in this case, we will process the event given
                                if ((processP2pEvt(lastP2pEvtStr) != -1) && (!lastP2pEvtStr.isEmpty())) {
                                    // this returns -1 on event process failure, which means here it has succeeded
                                    // to process this event.
                                    lastProcessedEvt = lastP2pEvtStr; // IMPORTANT, so that it won't invoke the callbacks for
                                                                      // that same event over and over again.
                                }
                            }
                        } catch (Throwable t) {
                            XposedBridge.log(TAG + "Error: Failed to read from file " + mP2pEvtRecentFFullPath + ", or process P2P Event: " + t.getMessage() + "; It is safe to ignore this error IF ONLY IT HAPPENED ONCE.");
                        }
                        // Poll wpa_cli for peers
                        Process process = Runtime.getRuntime().exec("wpa_cli -i wlan0 p2p_peers");
                        java.io.BufferedReader reader = new java.io.BufferedReader(
                                new java.io.InputStreamReader(process.getInputStream()));

                        java.util.Set<String> currentPeers = new java.util.HashSet<>();
                        String line;
                        while ((line = reader.readLine()) != null) {
                            line = line.trim();
                            // MAC address pattern: xx:xx:xx:xx:xx:xx
                            if (line.matches("^[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}$")) {
                                currentPeers.add(line.toLowerCase());
                            }
                        }
                        reader.close();
                        process.waitFor();

                        // Check for new peers
                        for (String peer : currentPeers) {
                            if (!existsInWifiP2pDeviceSet(peer, knownPeers)) {
                                XposedBridge.log(TAG + "New peer discovered: " + peer);
                                // Get detailed info about this peer
                                String[] peerInfoLines = getP2pPeerInfo(peer).split("\n");
//                                String peerInfo = getP2pPeerInfo(peer);
                                // now we will go through each discovered peer to construct a WifiP2pDevice object.
                                WifiP2pDevice p2pDevObj = new WifiP2pDevice();
//                                WifiP2pDevice p2pDevObj = new WifiP2pDevice("")
                                p2pDevObj.deviceAddress = peer;
                                // keep track of current configMethods value
                                int configMethods = 0;
                                // keep track of the current device Capabilities value.
                                int devCapabilities = 0;
                                // keep track of the current device Group Capabilities value.
                                int grpCapabilities = 0;
                                // storing the wfd_dev_info into some string value
                                String wfdsubelems = "";
                                // a flag that will tell us to ignore this current peer until a next iteration!
                                boolean ignoreThisPeer = false;
                                for (String infoLine : peerInfoLines) {
                                    String[] infoLineAsKVP = infoLine.split("=");
                                    // index 0 is the key name, index 1 is the value name, but this doesn't unfortunately always apply
                                    // for everything so we will make sure to omit those who don't have 2 indexes.
                                    if (infoLineAsKVP.length >= 2) {
                                        // now we have to start pushing data onto the WifiP2pDevice object p2pDevObj.
                                        switch (infoLineAsKVP[0]) {
                                            case "device_name":  // deviceName
                                                p2pDevObj.deviceName = infoLineAsKVP[1];
                                                break;
                                            case "status":  // status (int)
                                                // status is 0 for Available devices, but AOSP framework expects 3 for Available Status, so
                                                // we will set it to 3 when its Available instead.
                                                if ((int)Integer.parseInt(infoLineAsKVP[1]) == 0) {
                                                    p2pDevObj.status = 3;
                                                } else {
                                                    // we will just redirect the given code to the Framework as it is (not recommended)
                                                    p2pDevObj.status = (int) Integer.parseInt(infoLineAsKVP[1]);
                                                }
                                                break;
                                            case "pri_dev_type":
                                                p2pDevObj.primaryDeviceType = infoLineAsKVP[1];
                                                break;
                                            case "config_methods":
                                                try {
                                                    configMethods = Integer.decode(infoLineAsKVP[1]);
                                                } catch (NumberFormatException e) {
                                                    configMethods = 0;
                                                }
                                                break;
                                            case "flags":
                                                if (infoLineAsKVP[1].toLowerCase().contains("PROBE_REQ_ONLY".toLowerCase())) {
                                                    ignoreThisPeer = true; // we will ignore this peer
                                                                           // since this is only a result of a found broadcasted Probe Request.
                                                }
                                                break;
                                            case "dev_capab": // fill up the device capability field
                                                try {
                                                    devCapabilities = Integer.decode(infoLineAsKVP[1]);
                                                } catch (NumberFormatException e) {
                                                    devCapabilities = 0;
                                                }
                                                break;
                                            case "group_capab":
                                                try {
                                                    grpCapabilities = Integer.decode(infoLineAsKVP[1]);
                                                } catch (NumberFormatException e) {
                                                    grpCapabilities = 0;
                                                }
                                                break;
                                            case "wfd_subelems":
                                                wfdsubelems = infoLineAsKVP[1];
                                                break;
                                            default:
                                                break;
                                        }
                                    }
                                }
                                if (ignoreThisPeer) {
                                    XposedBridge.log(TAG + "Ignoring peer " + peer + ", Since this is a result of a broadcasted Probe Request!");
                                    continue;
                                }
                                // Try to set config_methods on the WifiP2pDevice using reflection
                                try {
                                    java.lang.reflect.Field configField = WifiP2pDevice.class.getField("wpsConfigMethodsSupported");
                                    configField.setInt(p2pDevObj, configMethods);
                                    XposedBridge.log(TAG + "Set wpsConfigMethodsSupported=" + configMethods + " for " + peer);
                                    // now we will fill up the Device capability field.
                                    java.lang.reflect.Field devCapabField = WifiP2pDevice.class.getField("deviceCapability");
                                    devCapabField.setInt(p2pDevObj, devCapabilities);
                                    XposedBridge.log(TAG + "Set deviceCapability=" + devCapabilities);
                                    // next up, we will fill up the Group capability field.
                                    java.lang.reflect.Field grpCapabField = WifiP2pDevice.class.getField("groupCapability");
                                    grpCapabField.setInt(p2pDevObj, grpCapabilities);
                                    XposedBridge.log(TAG + "Set groupCapability=" + grpCapabilities);
                                    // setting up the value for wfd_dev_info
                                    // if and ONLY if it was found.
                                    if (!wfdsubelems.isEmpty()) {
                                        java.lang.reflect.Field wfdInfoField = WifiP2pDevice.class.getField("wfdInfo");
                                        // construct a new WifiP2pWfdInfo using its public constructor that accepts a 3 integers.
                                        // but we will have to use Reflection to access this constructor.
                                        java.lang.reflect.Constructor<WifiP2pWfdInfo> wfdInfoObjConstructor = WifiP2pWfdInfo.class.getDeclaredConstructor(int.class, int.class, int.class);
                                        wfdInfoObjConstructor.setAccessible(true);

                                        String wfd_info_data = wfdsubelems.substring(6, 18);
                                        String wfd_device_role = wfd_info_data.substring(0, 4);
                                        String wfd_device_ctrl_port = wfd_info_data.substring(4, 8);
                                        String wfd_device_max_Tput = wfd_info_data.substring(8);
                                        // handle wfd_device_role
                                        int wfd_device_role_value = Integer.parseInt(wfd_device_role, 16);

                                        // public WifiP2pWfdInfo(int devInfo, int ctrlPort, int maxTput)
//                                        WifiP2pWfdInfo wfdInfoObj = wfdInfoObjConstructor.newInstance(wfd_device_role_value,
//                                                Integer.parseInt(wfd_device_ctrl_port, 16),
//                                                Integer.parseInt(wfd_device_max_Tput, 16));
                                        WifiP2pWfdInfo wfdInfoObj = wfdInfoObjConstructor.newInstance(
                                                wfd_device_role_value,
                                                Integer.parseInt(wfd_device_ctrl_port, 16),
                                                300 // assuming MAX Throughput of 300 MBit/s
                                        );
                                        // now let's assign this newely created wfdInfoObj to our wfdInfo field.
                                        wfdInfoField.set(p2pDevObj, wfdInfoObj);
                                        XposedBridge.log(TAG + "Set wfdInfo=WifiP2pWfdInfo(devInfo=" +
                                                wfd_device_role_value + ", ctrlPort=" +
                                                Integer.parseInt(wfd_device_ctrl_port, 16) + ", maxTput=" +
//                                                Integer.parseInt(wfd_device_max_Tput, 16) + ")");
                                                "300)");
                                    }
                                } catch (NoSuchFieldException e) {
                                    // Field doesn't exist in this Android version
                                    XposedBridge.log(TAG + "WARNING: Some field couldn't be found to properly construct a WifiP2pDevice object to pass to callback methods!");
                                    // Log all available fields for debugging
                                    for (java.lang.reflect.Field f : WifiP2pDevice.class.getFields()) {
                                        XposedBridge.log(TAG + "  Available field: " + f.getName());
                                    }
                                } catch (IllegalAccessException e) {
                                    XposedBridge.log(TAG + "Cannot access desired field: " + e.getMessage());
                                }
                                // we will add it to the set of known peers.
                                knownPeers.add(p2pDevObj);
                                injectP2pDeviceFound(peer, p2pDevObj);
                            }
                        }

                        // Check for removed peers
                        java.util.Set<WifiP2pDevice> removedPeers = new java.util.HashSet<>(knownPeers);
//                        removedPeers.removeAll(currentPeers);
                        for (String p : currentPeers) {
                            removedPeers.removeIf(p2pdev -> p2pdev.deviceAddress.equalsIgnoreCase(p.toLowerCase()));
                        }
                        for (WifiP2pDevice rpeer : removedPeers) {
                            XposedBridge.log(TAG + "Peer lost: " + rpeer.deviceAddress);
                            knownPeers.remove(rpeer);
                            injectP2pDeviceLost(rpeer);
                        }

                        // Sleep for 3 seconds before next poll
                        Thread.sleep(3000);

                    } catch (InterruptedException e) {
                        XposedBridge.log(TAG + "Polling thread interrupted");
                        break;
                    } catch (Exception e) {
                        XposedBridge.log(TAG + "Polling error: " + e.getMessage());
                        try {
                            Thread.sleep(3000);
                        } catch (InterruptedException ie) {
                            break;
                        }
                    }
                }

                XposedBridge.log(TAG + "Polling thread stopped");
            }
        });

        pollingThread.setDaemon(true);
        pollingThread.start();
    }

    private void stopP2pPeerPolling() {
        isPolling = false;
        if (pollingThread != null) {
            pollingThread.interrupt();
            pollingThread = null;
        }
    }

    // a method that checks if the MAC Address exists as a WifiP2pDevice object in a Set of WifiP2pDevice objects
    private boolean existsInWifiP2pDeviceSet(String searchFor, java.util.Set<WifiP2pDevice> WifiP2pDeviceSet) {
        // we will iterate over each WifiP2pDevice in the given set, if we find a WifiP2pDevice object that
        // holds the target MAC Address (searchFor) we will return true, otherwise we will return false.
        for (WifiP2pDevice p2pDev : WifiP2pDeviceSet) {
            if (p2pDev.deviceAddress.equalsIgnoreCase(searchFor.toLowerCase())) return true;
        }
        return false;
    }

    // Inject a P2P-DEVICE-FOUND event into WifiP2pMonitor
    private void injectP2pDeviceFound(String macAddress, WifiP2pDevice p2pDevice) {
        try {
            if (mMonitorInstance == null) {
                XposedBridge.log(TAG + "Monitor instance is null, cannot inject event");
                return;
            }

            // Get peer details from wpa_cli
            String peerInfo = getP2pPeerInfo(macAddress);
            if (peerInfo == null) {
                XposedBridge.log(TAG + "Could not get peer info for " + macAddress);
                return;
            }

            XposedBridge.log(TAG + "Injecting P2P-DEVICE-FOUND event: " + peerInfo);

            // Call broadcastP2pDeviceFound on WifiP2pMonitor
            Class<?> monitorClass = mMonitorInstance.getClass();

            // Find the method to broadcast device found
            java.lang.reflect.Method broadcastMethod = null;
            for (java.lang.reflect.Method m : monitorClass.getDeclaredMethods()) {
                if (m.getName().toLowerCase().contains("broadcastp2pdevicefound") ||
                        m.getName().toLowerCase().contains("devicefound")) {
                    broadcastMethod = m;
                    break;
                }
            }

            if (broadcastMethod == null) {
                // Fallback: Try to call dispatchEvent directly
                for (java.lang.reflect.Method m : monitorClass.getDeclaredMethods()) {
                    if (m.getName().toLowerCase().contains("dispatchevent")) {
                        broadcastMethod = m;
                        XposedBridge.log(TAG + "Using dispatchEvent as fallback");
                        break;
                    }
                }
            }

            if (broadcastMethod != null) {
                broadcastMethod.setAccessible(true);
                // Try different call signatures
                try {
                    // this is the method signature of
                    // public void broadcastP2pDeviceFound(String iface, WifiP2pDevice device)
                    // so it accepts an interface name (String) in the first parameter
                    // and a WifiP2pDevice object in the second parameter
                    // as per what the documentation says: https://developer.android.com/reference/android/net/wifi/p2p/WifiP2pDevice
                    broadcastMethod.invoke(mMonitorInstance, mInterfaceName, p2pDevice);
                } catch (Exception e1) {
//                    try {
//                        broadcastMethod.invoke(mMonitorInstance, "P2P-DEVICE-FOUND", mInterfaceName, peerInfo);
//                    } catch (Exception e2) {
                    XposedBridge.log(TAG + "Failed to invoke broadcast method: " + e1.getMessage());
//                    }
                }
            } else {
                XposedBridge.log(TAG + "Could not find broadcast method in WifiP2pMonitor");
            }

        } catch (Exception e) {
            XposedBridge.log(TAG + "Error injecting device found: " + e.getMessage());
        }
    }

    // Inject a P2P-DEVICE-LOST event
    private void injectP2pDeviceLost(WifiP2pDevice lostP2pDevObj) {
        try {
            if (mMonitorInstance == null) return;

            XposedBridge.log(TAG + "Injecting P2P-DEVICE-LOST event: " + lostP2pDevObj.deviceAddress);

            Class<?> monitorClass = mMonitorInstance.getClass();
            java.lang.reflect.Method broadcastMethod = null;

            for (java.lang.reflect.Method m : monitorClass.getDeclaredMethods()) {
                if (m.getName().toLowerCase().contains("broadcastp2pdevicelost") ||
                        m.getName().toLowerCase().contains("devicelost")) {
                    broadcastMethod = m;
                    break;
                }
            }

            if (broadcastMethod != null) {
                broadcastMethod.setAccessible(true);
                try {
                    broadcastMethod.invoke(mMonitorInstance, mInterfaceName, lostP2pDevObj);
                } catch (Exception e) {
                    XposedBridge.log(TAG + "Failed to invoke device lost: " + e.getMessage());
                }
            } else {
                XposedBridge.log(TAG + "ERROR: Failed to get method broadcastP2pDeviceLost()!!!");
            }

        } catch (Exception e) {
            XposedBridge.log(TAG + "Error injecting device lost: " + e.getMessage());
        }
    }

    // Get detailed peer information from wpa_cli
    private String getP2pPeerInfo(String macAddress) {
        try {
            Process process = Runtime.getRuntime().exec("wpa_cli -i wlan0 p2p_peer " + macAddress);
            java.io.BufferedReader reader = new java.io.BufferedReader(
                    new java.io.InputStreamReader(process.getInputStream()));

            StringBuilder info = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                info.append(line).append("\n");
            }
            reader.close();
            process.waitFor();

            return info.toString().trim();

        } catch (Exception e) {
            XposedBridge.log(TAG + "Error getting peer info: " + e.getMessage());
            return null;
        }
    }
    // A Method for handling/processing events received by the P2p Poller Thread from the /data/p2p_evt_recent file.
    // returns -1 on failure
    // a non-zero value on success (1)
    // -2 if the given Event string is empty (has the length of 0 characters)
    public int processP2pEvt(String p2pEvtStr) {
        if (p2pEvtStr.isEmpty()) return -2;
        // first of all, we have to retrieve all the desired methods we will be using for callbacks.
        java.lang.reflect.Method mBroadcastP2pProvisionDiscoveryPBCResp = null;
        java.lang.reflect.Method mBroadcastP2pProvisionDiscoveryEnterPIN = null;
        java.lang.reflect.Method mBroadcastP2pProvisionDiscoveryShowPIN = null;
        java.lang.reflect.Method mBroadcastP2pGroupStarted = null;
        // add other methods here as necessary.
        for (java.lang.reflect.Method m : mMonitorInstance.getClass().getDeclaredMethods()) {
            if (m.getName().toLowerCase().contains("p2pprovisiondiscoverypbcresponse")) {
                mBroadcastP2pProvisionDiscoveryPBCResp = m;
            }
            // add code to find other necessary callback methods here too.
            // for broadcastP2pProvisionDiscoveryEnterPIN()
            if (m.getName().toLowerCase().contains("p2pprovisiondiscoveryenterpin")) {
                mBroadcastP2pProvisionDiscoveryEnterPIN = m;
            }
            // for broadcastP2pProvisionDiscoveryShowPIN()
            if (m.getName().toLowerCase().contains("p2pprovisiondiscoveryshowpin")) {
                mBroadcastP2pProvisionDiscoveryShowPIN = m;
            }
            // for broadcastP2pGroupStarted()
            if (m.getName().toLowerCase().contains("p2pgroupstarted")) {
                mBroadcastP2pGroupStarted = m;
            }
        }
        // process p2p event string.
        try {
            if (p2pEvtStr.toLowerCase().contains("prov-disc")) {
                Class<?> clazz = Class.forName("android.net.wifi.p2p.WifiP2pProvDiscEvent");
                Constructor<?> constructor = clazz.getConstructor(String.class);
                constructor.setAccessible(true);
                // now our WifiP2pProvDiscEvent
                // we pass the string as it is to a constructor because it is able to extract event details from it.
                Object p2pProvDiscEvtObj = constructor.newInstance(p2pEvtStr);
                // now we check for the discovery provision response type:
                if (p2pEvtStr.toLowerCase().contains("p2p-prov-disc-pbc-resp")) {
                    // p2p provision discovery event push button connect response.
                    // all we have to do is just set the method to be accessible then just call it.
                    if (mBroadcastP2pProvisionDiscoveryPBCResp != null) {
                        try {
                            mBroadcastP2pProvisionDiscoveryPBCResp.setAccessible(true);
                            mBroadcastP2pProvisionDiscoveryPBCResp.invoke(mMonitorInstance, mInterfaceName, p2pProvDiscEvtObj);
                            return 1;
                        } catch (Throwable t) {
                            XposedBridge.log(TAG + "ERROR: Couldn't invoke method \"broadcastP2pProvisionDiscoveryPbcResponse()\": " + t.getMessage());
                            return -1;
                        }
                    } else {
                        XposedBridge.log(TAG + "ERROR: Failed to find method \"broadcastP2pProvisionDiscoveryPbcResponse()\", Ignoring this event! ");
                        return -1;
                    }
                } else if (p2pEvtStr.toLowerCase().contains("p2p-prov-disc-enter-pin")) {
                    if (mBroadcastP2pProvisionDiscoveryEnterPIN != null) {
                        try {
                            mBroadcastP2pProvisionDiscoveryEnterPIN.setAccessible(true);
                            mBroadcastP2pProvisionDiscoveryEnterPIN.invoke(mMonitorInstance, mInterfaceName, p2pProvDiscEvtObj);
                        } catch (Throwable t) {
                            XposedBridge.log(TAG + "Error: failed to invoke method \"broadcastP2pProvisionDiscoveryEnterPin()\": " + t.getMessage());
                            return -1;
                        }
                    } else {
                        XposedBridge.log(TAG + "Error: Couldn't find method \"broadcastP2pProvisionDiscoveryEnterPin()\"");
                        return -1;
                    }
                } else if (p2pEvtStr.toLowerCase().contains("p2p-prov-disc-show-pin")) {
                    if (mBroadcastP2pProvisionDiscoveryShowPIN != null) {
                        try {
                            mBroadcastP2pProvisionDiscoveryShowPIN.setAccessible(true);
                            mBroadcastP2pProvisionDiscoveryShowPIN.invoke(mMonitorInstance, mInterfaceName, p2pProvDiscEvtObj);
                        } catch (Throwable t) {
                            XposedBridge.log(TAG + "Error: failed to invoke method \"broadcastP2pProvisionDiscoveryShowPin()\": " + t.getMessage());
                            return -1;
                        }
                    } else {
                        XposedBridge.log(TAG + "Error: Couldn't find method \"broadcastP2pProvisionDiscoveryShowPin()\"");
                        return -1;
                    }
                } else {
                    XposedBridge.log(TAG + "WARNING: Provision Discovery Event of Unknown type received: " + p2pEvtStr + "\nIgnoring this event and marking it as processed...");
                    return 1;
                }
            } else if (p2pEvtStr.toLowerCase().contains("p2p-group-started")) {
                // but first we have to construct a WifiP2pGroup object
                WifiP2pGroup p2pGrp = new WifiP2pGroup();
                // the fields we want to directly access via reflection.
                java.lang.reflect.Field mInterface = WifiP2pGroup.class.getDeclaredField("mInterface");
                mInterface.setAccessible(true);
                java.lang.reflect.Field mIsGroupOwner = WifiP2pGroup.class.getDeclaredField("mIsGroupOwner");
                mIsGroupOwner.setAccessible(true);
                java.lang.reflect.Field mNetworkName = WifiP2pGroup.class.getDeclaredField("mNetworkName");
                mNetworkName.setAccessible(true);
                java.lang.reflect.Field mPassphrase = WifiP2pGroup.class.getDeclaredField("mPassphrase");
                mPassphrase.setAccessible(true);
                java.lang.reflect.Field mOwner = WifiP2pGroup.class.getDeclaredField("mOwner");
                mOwner.setAccessible(true);

                // we will fill it up using the code we found in the public String Constructor of WifiP2pGroup from the AOSP source
                String[] tokens = p2pEvtStr.split(" ");
                mInterface.set(p2pGrp, tokens[1]);
                mIsGroupOwner.set(p2pGrp, (tokens[2].equalsIgnoreCase("GO")));
                for (String token : tokens) {
                    String[] nameValue = token.split("=");
                    if (nameValue.length != 2) continue;
                    if (nameValue[0].equals("ssid")) {
                        mNetworkName.set(p2pGrp, nameValue[1]);
                        continue;
                    }
                    if (nameValue[0].equals("passphrase")) {
                        mPassphrase.set(p2pGrp, nameValue[1]);
                        continue;
                    }
                    if (nameValue[0].equals("go_dev_addr")) {
                        // we will have to generate a new WifiP2pDevice using the same logic we had in startP2pPeerPolling.
                        WifiP2pDevice eP2pDev = new WifiP2pDevice();
                        eP2pDev.deviceAddress = nameValue[1];
                        mOwner.set(p2pGrp, eP2pDev);
                    }
                }
                // we've received a p2p group started event!
                if (mBroadcastP2pGroupStarted != null) {
                    try {
                        mBroadcastP2pGroupStarted.setAccessible(true);
                        mBroadcastP2pGroupStarted.invoke(mMonitorInstance, mInterfaceName, p2pGrp);
                    } catch (Throwable t) {
                        XposedBridge.log(TAG + "Error: failed to invoke method: \"broadcastP2pGroupStarted()\": " + t.getMessage());
                        return -1;
                    }
                } else {
                    XposedBridge.log(TAG + "Error: Couldn't find method \"broadcastP2pGroupStarted()\"");
                    return -1;
                }
            } else {
                // any other unknown event to us.
                XposedBridge.log(TAG + "Ignoring P2P Event: " + p2pEvtStr);
                return 1; // to ignore it (to  list it as previously processed)
            }
        } catch (Throwable t) {
            XposedBridge.log(TAG + "Error: Couldn't process p2p event: " + p2pEvtStr + '\n' + "Due to error: " + t.getMessage());
            return -1;
        }
        return 2; // indicating success
    }

}